env:
  global:
  - FILE_NAME="TCC_FGA.pdf"
  - RELEASE_NAME="RELATORIO_RADOP-v$TRAVIS_BUILD_NUMBER.pdf"
sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-full
  texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
  make
script:
- make clean
- make
- mkdir build/
- mv $FILE_NAME $RELEASE_NAME
- mv $RELEASE_NAME build/
deploy:
  provider: releases
  api_key:
    secure: N+a83CGm56D+nteMw5yNVdv+dLSJ/4DEwlwW8hau5u075OiIUWqzC9hiusPOAY1FRI3VzM03SPYq2zz7L8bBVK9ko3TGyTQWWOC+Mbg56h1CDhWIUPZIcjchJmHqm4OvFTIlKtt6sJVa8792UmMibKv8gt2O8KOJY+0x13TpafUFev5o+7rBA8656qgRrY+JnMkr2Ble4CkghLshceVe2kAo+chWhLDuk5PFWjFVGRACLKUjEnrwjvyINT/uPft5JSziqG4Gltf2zZZDmLYE5h9+SAcrV3Vp5HzxyYN3d5dZAU205XKwX+zaXLXAtW0IQq4PaBQMUXPB5aXievyCSVRdGulFmSBLGSriKJEVbVn74AQUUe2eFxItE2vfPTH7M2QQU2WzgU4bvc80MkyR505k4Nxd8mg1XUp7c/0llB06F1XQFqiuQrwuy3KQgpO2tQqQEzOVytjYuv6C3JHX47U8j5wTQRei4DnKoZLqam2pk3XICEgsdcl/P0yiXwY3rQl/NthlB2vf9bxya2shAzYsYHza5GG9rAZfUasYm2Aw1YcFq6xv9Kw69+L1fpnOvTgJ5uQ/HDOsdJgLlQPQj4gLDVMGcfTHoBiuVpHtqOG4I0bE0AiV9vZ6N3xJJi0STZklXs35mH7wnDp0tq0mM3yLVaNbUk4tBSGmoei+LTI=
  file_glob: true
  file: build/*
  skip_cleanup: true
  on:
    repo: radar-pi/relatorios
    branch: master
